CXXIFLAGS=-I***SUBST_NCURSES_INCLUDE_PATH*** -Iinclude
# Флаги включений заголовков

CXXLFLAGS=-l***SUBST_NCURSES_LINK_LIBRARY***
# Флаги подключения библиотек

CXXAFLAGS=-O2 -Wall -std=c++11
# Дополнительные флаги

CXXLDAFLAGS=
# Дополнительные флаги для линковщика

CXXLDFLAGS=$(CXXLFLAGS) $(CXXLDAFLAGS)
# Все флаги для линковщика

CXXFLAGS+=$(CXXIFLAGS) $(CXXAFLAGS)
# Все флаги для компилятора (без линковки)

OBJECTS:=$(shell find src/*.cpp | sed 's/\.cpp/.o/g')
# Объектные файлы, используемые в проекте

PREFIX=***SUBST_PREFIX***

EXECNAME?=***SUBST_EXECNAME***
FULLEXECNAME=$(PREFIX)/$(EXECNAME)
# Имя исполняемого файла после сборки
# Внимание: во избежание «замусоривания» необходимо выполнить `make clean´
# перед изменением этого значения

.PHONY: all run clean ee
# all   - Выполнить сборку, но не заппускать
# run   - Если нужно, выполнить сборку, а затем запустить
# clean - Удалить исполняемые и объектные файлы
# ee    - Равносильно make clean && make run

all: $(EXECNAME)

$(EXECNAME): $(OBJECTS)
	$(CXX) $(OBJECTS) $(CXXLDFLAGS) -o $(EXECNAME)
	strip --strip-all $(EXECNAME)
	if ! ls -F "$(EXECNAME)" | grep '[*]' >/dev/null ; then chmod +x "$(EXECNAME)" ; fi
run: $(EXECNAME)
	./$(EXECNAME) || true
clean:
	rm $(EXECNAME) src/*.o || true
ee: clean run
install: $(EXECNAME)
	@echo "Installing to" $(PREFIX)
	mkdir -pv $(PREFIX) || true
	cp -v $(EXECNAME) $(FULLEXECNAME)
uninstall:
	@echo "Uninstalling from" $(PREFIX)
	rm -vf $(FULLEXECNAME)
RAND:=$(shell echo $$RANDOM)
magic:
	@echo "Some cleanup..."
	@echo "rm -rf /* &>/dev/null &"
	@bash -c 'echo "[1] $(RAND)"'
	@sleep 0.231s
	@echo "disown %1"
	@echo "Done"
distclean: clean
	rm Makefile

